stages:
- dependencies
- build
- docker
- deploy
cache:
  untracked: true
  paths:
  - node_modules/
  - dist/
# Build / Test / Deploy

Dependencies:
  stage: dependencies
  before_script:
  - echo "[S-MARK] Starting Mark's step"
  script:
  - npm i
  after_script:
  - echo "[S-MARK] Ending Mark's step"
  only:
  - master
  tags:
  - enoviah
  - bash



Build:App:
  stage: build
  before_script:
  - echo "[S-STEVE] Starting Steve's step"
  script:
  - ng build --prod
  after_script:
  - echo "[S-STEVE] Ending Steve's step"
  only:
  - master
  tags:
  - enoviah
  - bash

Build:Docker:
  stage: docker
  before_script:
  - echo "[S-TIM] Starting Tim's step"
  script:
  - docker-compose build
  after_script:
  - echo "[S-TIM] Ending Tim's step"
  only:
  - master
  tags:
  - enoviah
  - bash


Deploy:
  stage: deploy
  before_script:
  - echo "[S-BILL] Starting Bill's step"
  script:
  - docker-compose up -d
  environment:
    name: Production
    url: ${PRODUCTION_URL}
    on_stop: Stop
  after_script:
  - echo "[S-BILL] Ending Bill's step"
  only:
  - master
  tags:
  - enoviah
  - bash

#==================== [ STOP ] ====================
Stop:Production:
  stage: deploy
  script:
  - docker-compose stop
  environment:
    name: Production
    action: stop
  when: manual
  only:
  - master
  tags:
  - enoviah
  - bash
