version: '3'
services:
  assistant-epitech:
    build:
      context: .
    image: assistant-epitech:webapp
    restart: always
    container_name: ${CI_PROJECT_NAME}
    ports:
    - ${PORT}:80
    environment:
    - PORT=${PORT}
    - CI_PROJECT_NAME=${CI_PROJECT_NAME}
