version: '3'
services:
  epitech-assistant:
    build:
      context: .
    image: epitech-assistant:webapp
    restart: always
    container_name: epitech-assistant-webapp
    ports:
    - ${PORT}:80
    environment:
    - PORT=${PORT}
