version: '3'
services:
  assistant-epitech-front:
    build:
      context: .
    restart: always
    container_name: ${CI_PROJECT_NAME}
    ports:
    - ${PORT}:80
    environment:
    - PORT=${PORT}
    - CI_PROJECT_NAME=${CI_PROJECT_NAME}
